source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train-obfuscates_id.gemspec.
gemspec

gem "sqlite3", "< 2"

gem "sprockets-rails"

group :test do
  gem "minitest-reporters"
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
