# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in bullet_train-scope_validator.gemspec
gemspec

gem "rake", "~> 13.0"

group :test do
  gem "minitest-reporters"
end
