source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train-integrations-stripe.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

gem "bullet_train", path: "../bullet_train"
gem "bullet_train-api", path: "../bullet_train-api"
gem "bullet_train-fields", path: "../bullet_train-fields"
gem "bullet_train-super_scaffolding", path: "../bullet_train-super_scaffolding"
gem "bullet_train-incoming_webhooks", path: "../bullet_train-incoming_webhooks"

group :test do
  gem "minitest-reporters"
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
