ActiveSupport::Inflector.inflections(:en) do |inflect|
  # "_by" is a particularly common suffix for associations in Bullet Train applications (e.g. `created_by`, etc.)
  # but it gets pluralized incorrectly as "_bies". This should fix both Super Scaffolding for those fields and
  # the resulting invocations of the scope validator that are generated by Super Scaffolding.
  inflect.irregular "by", "bys"
end
