source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train-outgoing_webhooks.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

gem "jbuilder"

gem "bullet_train", path: "../bullet_train"
gem "bullet_train-api", path: "../bullet_train-api"
gem "bullet_train-fields", path: "../bullet_train-fields"
gem "bullet_train-super_scaffolding", path: "../bullet_train-super_scaffolding"
gem "bullet_train-has_uuid", path: "../bullet_train-has_uuid"
gem "bullet_train-roles", path: "../bullet_train-roles"
gem "bullet_train-scope_validator", path: "../bullet_train-scope_validator"
gem "bullet_train-super_load_and_authorize_resource", path: "../bullet_train-super_load_and_authorize_resource"
gem "bullet_train-themes", path: "../bullet_train-themes"

group :test do
  gem "minitest-reporters"
  gem "webmock"
end
