source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train-outgoing_webhooks.gemspec.
gemspec

gem "pg", "~> 1.1"

gem "sprockets-rails"

gem "jbuilder"
# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
