source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train-fields.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

gem "bullet_train", path: "../bullet_train"
gem "bullet_train-api", path: "../bullet_train-api"
gem "bullet_train-super_scaffolding", path: "../bullet_train-super_scaffolding"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
