source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

# TODO Have to specify this dependency here until our changes are in the original package.
gem "active_hash", github: "bullet-train-co/active_hash"

gem "commonmarker", ">= 1.0.0.pre10"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
