source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

# TODO Have to specify this dependency here until our changes are in the original package.
gem "active_hash", github: "bullet-train-co/active_hash"

gem "commonmarker", ">= 1.0.0.pre10"

gem "bullet_train-api", path: "../bullet_train-api"
gem "bullet_train-fields", path: "../bullet_train-fields"
gem "bullet_train-roles", path: "../bullet_train-roles"
gem "bullet_train-super_scaffolding", path: "../bullet_train-super_scaffolding"
gem "bullet_train-super_load_and_authorize_resource", path: "../bullet_train-super_load_and_authorize_resource"
gem "bullet_train-themes-light", path: "../bullet_train-themes-light"
gem "bullet_train-has_uuid", path: "../bullet_train-has_uuid"
gem "bullet_train-scope_validator", path: "../bullet_train-scope_validator"
gem "bullet_train-themes", path: "../bullet_train-themes"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
