source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bullet_train.gemspec.
gemspec

gem "sqlite3"

gem "sprockets-rails"

gem "bullet_train-api", path: "../bullet_train-api"
gem "bullet_train-fields", path: "../bullet_train-fields"
gem "bullet_train-roles", path: "../bullet_train-roles"
gem "bullet_train-super_scaffolding", path: "../bullet_train-super_scaffolding"
gem "bullet_train-super_load_and_authorize_resource", path: "../bullet_train-super_load_and_authorize_resource"
gem "bullet_train-themes-light", path: "../bullet_train-themes-light"
gem "bullet_train-has_uuid", path: "../bullet_train-has_uuid"
gem "bullet_train-scope_validator", path: "../bullet_train-scope_validator"
gem "bullet_train-themes", path: "../bullet_train-themes"
gem "bullet_train-themes-tailwind_css", path: "../bullet_train-themes-tailwind_css"

# NOTE: This is an optional dependency in the starter repo. We only use it in one method that we don't
# actually ever call, either in the starter repo or in any of the core gems. We list it here so that it's
# available for tests/CI
gem "unicode-emoji", group: :test

group :test do
  gem "minitest-reporters"
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
