name: "Release Ruby Gems & NPM Packages"

on:
  workflow_dispatch:
  release:
    types:
      - created
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v3"

    - uses: "ruby/setup-ruby@v1"
      with:
        bundler-cache: true
        ruby-version: 3.2

    - uses: "actions/setup-node@v3"
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: "Setup ruby gems credentials file"
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials

    - name: "Install bump"
      run: gem install bump

    - name: "Release all"
      run: ./bin/release-all
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        NODE_AUTH_TOKEN: "${{secrets.NPM_AUTH_TOKEN}}"
